name = "Rank2BinaryForms"
uuid = "e83c4f86-926c-40f1-8a17-25e316e7ef75"
authors = ["Laura Brustenga i Moncusí <brust@math.ku.dk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
